# Generated by Django 4.1.7 on 2023-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('genre', models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY'), ('THRILLER', 'THRILLER'), ('ROMAN', 'ROMAN'), ('DETECTIVE', 'DETECTIVE'), ('ADVENTURE', 'ADVENTURE')], max_length=100, verbose_name='Жанр')),
                ('link', models.URLField(verbose_name='Ссылка на книгу')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('mass', models.PositiveIntegerField(verbose_name='Масса книги в граммах')),
                ('age_limit', models.PositiveIntegerField(verbose_name='Возрастное ограничение')),
                ('created_dates', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dates', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
