# Generated by Django 4.1.7 on 2023-02-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_ratingbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingbook',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
